from django.db import migrations, models
import django.db.models.deletion
class Migration(migrations.Migration):
 initial=True; dependencies=[]
 operations=[
 migrations.CreateModel(name='Customer',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('customer_number',models.CharField(max_length=32,unique=True)),('name',models.CharField(max_length=120)),('email',models.EmailField(max_length=254))]),
 migrations.CreateModel(name='Bill',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('bill_number',models.CharField(max_length=32,unique=True)),('amount',models.DecimalField(decimal_places=2,max_digits=12)),('due_date',models.DateField()),('status',models.CharField(choices=[('UNPAID','Unpaid'),('PAID','Paid')],default='UNPAID',max_length=10)),('customer',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='bills',to='payments.customer'))]),
 migrations.CreateModel(name='Payment',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('provider_reference',models.CharField(max_length=64,unique=True)),('amount',models.DecimalField(decimal_places=2,max_digits=12)),('provider_status',models.CharField(choices=[('SUCCESS','Success'),('FAILED','Failed'),('PENDING','Pending'),('TIMEOUT','Timeout')],max_length=10)),('reconciliation_status',models.CharField(choices=[('PENDING','Pending'),('RECONCILED','Reconciled'),('FAILED','Failed'),('MANUAL_REVIEW','Manual Review')],default='PENDING',max_length=20)),('created_at',models.DateTimeField(auto_now_add=True)),('reconciled_at',models.DateTimeField(blank=True,null=True)),('last_error',models.TextField(blank=True)),('bill',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='payments',to='payments.bill'))]),
 migrations.CreateModel(name='ReconciliationEvent',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('action',models.CharField(max_length=40)),('previous_status',models.CharField(blank=True,max_length=20)),('new_status',models.CharField(blank=True,max_length=20)),('message',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('payment',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='events',to='payments.payment'))]) ]
