# Generated by Django 5.1.7 on 2026-09-08 06:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_bill_amount_positive'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='next_attempt_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='simulated_timeouts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of temporary timeouts before the configured provider result (0-3).'),
        ),
        migrations.AddField(
            model_name='payment',
            name='timeout_attempts',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='bill',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='payments.customer'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.bill'),
        ),
        migrations.AlterField(
            model_name='reconciliationevent',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='payments.payment'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['reconciliation_status', 'next_attempt_at'], name='payment_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['UNPAID', 'PAID'])), name='bill_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('provider_status__in', ['SUCCESS', 'FAILED', 'PENDING', 'TIMEOUT'])), name='provider_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('reconciliation_status__in', ['PENDING', 'RECONCILED', 'FAILED', 'MANUAL_REVIEW'])), name='reconciliation_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('simulated_timeouts__lte', 3)), name='simulated_timeouts_bounded'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('reconciliation_status', 'RECONCILED')), fields=('bill',), name='one_reconciled_payment_per_bill'),
        ),
    ]
